# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
# image: angular/ngcontainer


stages:          # List of stages for jobs, and their order of execution
  - build
  - package

build-job:       # This job runs in the build stage, which runs first.
  image: robindbl/angular-cli
  stage: build
  artifacts:
    paths:
      - dist/*
    expire_in: 1 hour
  script:
    - echo "Compiling the code..."
    - npm install
    - ng build
    - echo "Compile complete."


services:
    - name: docker:18.09.7-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
    
variables:
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""

build-docker-container:

  before_script:
    - docker info
  
  image: docker:19.03.12
  stage: package
  needs: 
    - job: build-job
      artifacts: true
  script:
    - docker login -u robindbl -p bd0ddb2a-5b67-4ce2-8ad9-4dce3898d74a
    - docker build -t robindbl/lr-culinair:latest .
    - docker push robindbl/lr-culinair:latest
